# config.yml
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://janseidler.github.io/
publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - label: 'Blog'
    name: 'blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    # updated fields in blog collection configuration
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Authors'
    name: 'authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Pages'
    name: 'pages'
    folder: 'pages/'
    editor:
      preview: false
  - label: 'About Page'
    name: 'about'
    folder: '_site/about/'
    fields:
      - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
      - { label: 'Body', name: 'body', widget: 'markdown' }